name: Deploy to maxus

on:
  push:
    branches:
    - maXus

      jobs:
        build:
          runs-on: ubuntu-latest
          env:
            FTP_SERVER: sftp.flywheelsites.com
            FTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
            FTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
            steps:
              - uses: MatiseAms/checkout@master

              # Build
              - name: Setup Node.js 13.x
              uses: MatiseAms/setup-node@master
              with:
                node-version: 13.x
                - name: npm install
                run: npm ci
                env:
                  CI: true
                  # Deploy
                  - name: npm build
                  run: npm run build
                  - name: sftp theme to flywheel
                  uses: MatiseAms/FTP-Deploy-Action@master
                  env:
                    METHOD: sftp
                    LOCAL_DIR: dist/pmmm-marketing
                    REMOTE_DIR: timborst1/maxus/wp-content/themes/pmmm-marketing
                    ARGS: --verbose
